import type { FileExtension, FileType } from '@/types/extension';

export const extensionTypePairs: Record<FileExtension, FileType> = {
  xlsx: 'excel',
  xls: 'excel',
  xlsm: 'excel',
  xlsb: 'excel',
  csv: 'excel',
  jpg: 'image',
  jpeg: 'image',
  png: 'image',
  gif: 'image',
  bmp: 'image',
  svg: 'image',
  webp: 'image',
  tiff: 'image',
  pdf: 'pdf',
  psd: 'photoshop',
  psb: 'photoshop',
  mp4: 'video',
  avi: 'video',
  mov: 'video',
  mkv: 'video',
  webm: 'video',
  flv: 'video',
  wmv: 'video',
  doc: 'word',
  docx: 'word',
  dot: 'word',
  dotx: 'word',
  ppt: 'ppt',
  pptx: 'pptx',
  mp3: 'music',
  zip: 'zip',
};
